version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ictcoop
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports :
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8010:8080
    depends_on:
      - db
